#! /usr/bin/env python
import os

def build(bld):
    bld.program(
        source = ['paki.c'],
        target = 'dhpak' + bld.env.SUFFIX,
        install_path = '${PREFIX}/bin',
        use = ['dhcore'])

