#! /usr/bin/env python

import os, sys

def build(bld):
    files = bld.path.ant_glob('*.c')
    files.extend(bld.path.ant_glob('components/*.c'))
    files.extend(bld.path.ant_glob('luabind/*.c*'))
    files.extend(bld.path.ant_glob('physx/*.c*'))
    files.extend(bld.path.ant_glob('renderpaths/*.c'))

    libs = []
    libpath = []
    includes = []
    frameworks = []
    linkflags = []

    if sys.platform == 'linux' or sys.platform == 'darwin':
        libs.extend([\
            'X11', 'Xi', 'Xrandr', 'Xxf86vm',
            'PhysX3Extensions',
            'PhysX3',
            'SimulationController',
            'PxTask',
            'PhysXProfileSDK',
            'LowLevel',
            'LowLevelCloth',
            'SceneQuery',
            'PhysX3Common',
            'PhysX3CharacterKinematic',
            'PhysX3Vehicle',
            'PhysX3Cooking',
            'RepX3'])
    elif sys.platform == 'win32':
        rel_suffix = ''
        if '_DEBUG_' in bld.env.DEFINES:    rel_suffix = 'DEBUG'
        if bld.env.DEST_CPU == 'amd64' or bld.env.DEST_CPU == 'x86_64':  arch_suffix = '_x64'
        else:            arch_suffix = '_x86'
        libs.extend([\
            'Gdi32', 'User32', 'Advapi32',
            'PhysX3' + rel_suffix + arch_suffix,
            'PhysX3Common' + rel_suffix + arch_suffix,
            'PhysX3Extensions' + rel_suffix,
            'PhysXProfileSDK' + rel_suffix])

    if sys.platform == 'win32':
        linkflags.extend(['/NODEFAULTLIB:"LIBCMTD.LIB"', '/NODEFAULTLIB:"LIBCMT.LIB"'])
    elif sys.platform == 'darwin':
        frameworks.extend(['Cocoa', 'CoreFoundation', 'CoreVideo', 'IOKit', 'OpenGL'])

    if bld.env.GFX_API == 'D3D':
        files.extend(bld.path.ant_glob('d3d/*.c*'))
        if bld.env.DX_LIBPATH != '':        libpath.append(bld.env.DX_LIBPATH)
        if bld.env.DX_INCLUDES != '':       includes.append(bld.env.DX_INCLUDES)
        libs.extend(['d3dcompiler', 'dxguid', 'd3d11'])
        files.append('platform/win/input-win.c')
    elif bld.env.GFX_API == 'GL':
        files.extend(bld.path.ant_glob('gl/*.c'))
        if sys.platform == 'linux':            libs.append('GL')
        elif sys.platform == 'win32':          libs.append('OpenGL32')
        libs.append('GLEW')

    includes.extend([\
        os.path.join(bld.env.ROOTDIR, 'build'),
        os.path.join(bld.env.ROOTDIR, 'include', 'dheng'),
        bld.env.PHYSX_INCLUDES,
        os.path.join(bld.env.PREFIX, 'include', 'lua')])

    libpath.append(bld.env.PHYSX_LIBPATH)
    
    # other 3rdparty
    libs.append('lua')

    # default target name and install path
    cflags = []
    if sys.platform == 'win32':
        cflags.append('/TP')

    vnum = ''
    if sys.platform == 'linux':
        vnum = bld.env.VERSION

    if sys.platform != 'win32':
        install_path = '${PREFIX}/lib'
    else:
        install_path = '${PREFIX}/bin'
        
    defines = ['_ENGINE_EXPORT_']
    if sys.platform == 'win32':     defines.append('LUA_BUILD_AS_DLL')

    bld.shlib(
        source = files,
        name = 'dheng',
        target = 'dheng' + bld.env.SUFFIX,
        install_path = install_path,
        defines = defines,
        lib = libs,
        cflags = cflags,
        libpath = libpath,
        includes = includes,
        framework = frameworks,
        linkflags = linkflags,
        vnum = vnum,
        use = ['dhcore', 'dhapp', '3rdparty_mongoose'])

