#! /usr/bin/env python

def build(bld):
    bld.program(
        source = ['main.cpp'],
        target = 'game-test' + bld.env.SUFFIX,
        install_path = '${PREFIX}/bin' if (bld.env.PREFIX == bld.env.ROOTDIR) else \
            '${PREFIX}/bin/dark-hammer',
        lib = ['dhcore' + bld.env.SUFFIX],
        use = ['dhapp', 'dheng'])
