
/***********************************************************************************
 * Copyright (c) 2014, Sepehr Taghdisian
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, 
 * are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, 
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation 
 *   and/or other materials provided with the distribution.
 *
 ***********************************************************************************/
 
  /**
  * Notice: This file is automatically generated with 'darkhammer/pytools/make-shvars' tool
  */

#define GFX_SHADERNAME_c_ambient_sky 3404474569 /* c_ambient_sky */
#define GFX_SHADERNAME_c_lightcolor 564242934 /* c_lightcolor */
#define GFX_SHADERNAME_c_params 874803984 /* c_params */
#define GFX_SHADERNAME_s_rgbl 2806384855 /* s_rgbl */
#define GFX_SHADERNAME_c_lightdirinv_vs 478830645 /* c_lightdirinv_vs */
#define GFX_SHADERNAME_c_viewproj 831640058 /* c_viewproj */
#define GFX_SHADERNAME_s_mtl_ambientmap 2673972560 /* s_mtl_ambientmap */
#define GFX_SHADERNAME_s_mtl_alphamap 271850052 /* s_mtl_alphamap */
#define GFX_SHADERNAME_c_mtl_props 3465801509 /* c_mtl_props */
#define GFX_SHADERNAME_c_grid 1805091443 /* c_grid */
#define GFX_SHADERNAME_s_lum_target 977875570 /* s_lum_target */
#define GFX_SHADERNAME_c_mtlidx 811880602 /* c_mtlidx */
#define GFX_SHADERNAME_s_color 2816991533 /* s_color */
#define GFX_SHADERNAME_c_lum_range 2096594651 /* c_lum_range */
#define GFX_SHADERNAME_c_mtl_ambientclr 4162480362 /* c_mtl_ambientclr */
#define GFX_SHADERNAME_s_mtl_reflectionmap 793714651 /* s_mtl_reflectionmap */
#define GFX_SHADERNAME_c_lightdir 103694982 /* c_lightdir */
#define GFX_SHADERNAME_s_norm_hires 1025839524 /* s_norm_hires */
#define GFX_SHADERNAME_c_views 3387306753 /* c_views */
#define GFX_SHADERNAME_s_norm 4200649640 /* s_norm */
#define GFX_SHADERNAME_c_mtlmax 721890431 /* c_mtlmax */
#define GFX_SHADERNAME_c_lastmip 2745685943 /* c_lastmip */
#define GFX_SHADERNAME_c_mats 267559782 /* c_mats */
#define GFX_SHADERNAME_s_tex 3524135785 /* s_tex */
#define GFX_SHADERNAME_c_rtvsz 1190044997 /* c_rtvsz */
#define GFX_SHADERNAME_c_skydir_vs 723502659 /* c_skydir_vs */
#define GFX_SHADERNAME_c_mtl_emissiveclr 2006322201 /* c_mtl_emissiveclr */
#define GFX_SHADERNAME_tb_mtls 1648725194 /* tb_mtls */
#define GFX_SHADERNAME_s_lum_adapted 778809376 /* s_lum_adapted */
#define GFX_SHADERNAME_c_shadow_mats 1125515140 /* c_shadow_mats */
#define GFX_SHADERNAME_s_shadowmap 2725063933 /* s_shadowmap */
#define GFX_SHADERNAME_s_depth 1248506876 /* s_depth */
#define GFX_SHADERNAME_c_color 1603163645 /* c_color */
#define GFX_SHADERNAME_c_type 2860030421 /* c_type */
#define GFX_SHADERNAME_tb_skins 3711976677 /* tb_skins */
#define GFX_SHADERNAME_s_mtl_emissivemap 3783117619 /* s_mtl_emissivemap */
#define GFX_SHADERNAME_c_mtl_diffuseclr 1289263652 /* c_mtl_diffuseclr */
#define GFX_SHADERNAME_s_mtl 708642965 /* s_mtl */
#define GFX_SHADERNAME_s_depth_ext 312145274 /* s_depth_ext */
#define GFX_SHADERNAME_c_view 3662453126 /* c_view */
#define GFX_SHADERNAME_c_cascade_planes 2829912095 /* c_cascade_planes */
#define GFX_SHADERNAME_tb_lights 1934874268 /* tb_lights */
#define GFX_SHADERNAME_c_texelsz 2248459662 /* c_texelsz */
#define GFX_SHADERNAME_c_rtsz 2023443248 /* c_rtsz */
#define GFX_SHADERNAME_c_mtl_specularclr 4157169392 /* c_mtl_specularclr */
#define GFX_SHADERNAME_c_camprops 1963083009 /* c_camprops */
#define GFX_SHADERNAME_c_cascades_vs 1541496903 /* c_cascades_vs */
#define GFX_SHADERNAME_c_celloffset 1650603969 /* c_celloffset */
#define GFX_SHADERNAME_c_kernel 732677592 /* c_kernel */
#define GFX_SHADERNAME_c_viewinv 3337918256 /* c_viewinv */
#define GFX_SHADERNAME_s_depth_hires 1886751948 /* s_depth_hires */
#define GFX_SHADERNAME_c_tiles 836977556 /* c_tiles */
#define GFX_SHADERNAME_c_max_far 3541512727 /* c_max_far */
#define GFX_SHADERNAME_c_ambient_ground 3318127920 /* c_ambient_ground */
#define GFX_SHADERNAME_s_shadows 3996731951 /* s_shadows */
#define GFX_SHADERNAME_s_ssao 2684231817 /* s_ssao */
#define GFX_SHADERNAME_s_mtl_diffusemap 3862286730 /* s_mtl_diffusemap */
#define GFX_SHADERNAME_s_albedo 1255117172 /* s_albedo */
#define GFX_SHADERNAME_s_add1 1431054806 /* s_add1 */
#define GFX_SHADERNAME_c_orthoparams 2274679921 /* c_orthoparams */
#define GFX_SHADERNAME_s_billboard 3094104843 /* s_billboard */
#define GFX_SHADERNAME_s_lum 3908641268 /* s_lum */
#define GFX_SHADERNAME_c_ambient_intensity 2750237388 /* c_ambient_intensity */
#define GFX_SHADERNAME_c_texelsize 1610159407 /* c_texelsize */
#define GFX_SHADERNAME_c_fovfactors 1583089152 /* c_fovfactors */
#define GFX_SHADERNAME_c_cascade_mats 3804834320 /* c_cascade_mats */
#define GFX_SHADERNAME_s_viewmap 146163049 /* s_viewmap */
#define GFX_SHADERNAME_c_midgrey 3041572094 /* c_midgrey */
#define GFX_SHADERNAME_s_bmp 145546078 /* s_bmp */
#define GFX_SHADERNAME_c_gloss 1036904885 /* c_gloss */
#define GFX_SHADERNAME_s_mtl_normalmap 698251941 /* s_mtl_normalmap */
#define GFX_SHADERNAME_c_projparams 446435409 /* c_projparams */
#define GFX_SHADERNAME_c_camfar 159983911 /* c_camfar */
#define GFX_SHADERNAME_c_elapsedtm 2887808162 /* c_elapsedtm */
#define GFX_SHADERNAME_c_world 1707161406 /* c_world */
#define GFX_SHADERNAME_s_noise 2521236077 /* s_noise */
