#! /usr/bin/env python

def build(bld):
    bld.recurse('core')
    bld.recurse('engine')
    if not bld.env.IGNORE_TOOLS:
        bld.recurse('h3dimport')
        bld.recurse('paki')
    if not bld.env.IGNORE_TESTS:
        bld.recurse('unit-test')
        bld.recurse('game-test')
